// Serverless utilitário para acessar o Supabase Admin API (Node)
import { createClient } from '@supabase/supabase-js';

// Usar as mesmas variáveis que funcionam no webhook
const supabaseUrl = process.env.VITE_SUPABASE_URL || 'https://tmucbwlhkffrhtexmjze.supabase.co';
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsImtpZCI6ImZNclU3TjVIVGpXakFzMXUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3RtdWNid2xoa2Zmcmh0ZXhtanplLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmM2U2MTdlZC1iZjQ0LTQ4YzAtYTM5ZC1hODRhYTU5Y2RhN2QiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoyMDQ2MTI0NzQzLCJpYXQiOjE3MzA1Njg3NDMsImVtYWlsIjoiZWR1YXJkb2ZyYWdhZGVtZWxsb0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJlbWFpbCIsInRpbWVzdGFtcCI6MTczMDU2ODc0M31dLCJzZXNzaW9uX2lkIjoiYzYzOTg1Y2ItOTAwZC00MzNjLWEzNDItYWU3Y2ZhNGFkNGY1IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.rNx8GkxpEeGjtOwYC_LiL4HlAiwZKVMPTRrCqt7UHVo';

export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey);
